" inspired by k-vim 
" 开启语法高亮
syntax on

" install bundles
if filereadable(expand("~/.vimrc.bundles"))
  source ~/.vimrc.bundles
elseif filereadable(expand("~/.config/nvim/vimrc.bundles")) " neovim
  source ~/.config/nvim/vimrc.bundles
endif

" ensure ftdetect et al work by including this after the bundle stuff
filetype plugin indent on


" history存储容量
set history=2000

" 检测文件类型
filetype on

" 设置新文件的编码为 UTF-8
set encoding=utf-8

" 针对不同的文件类型采用不同的缩进格式
filetype indent on
" 允许插件
filetype plugin on
" 启动自动补全
filetype plugin indent on

" 文件修改之后自动载入
set autoread

" 取消备份。 视情况自己改
set nobackup
" 关闭交换文件
set noswapfile

set wildignore=*.swp,*.bak,*.pyc,*.class,.svn,.git

" 设置 退出vim后，内容显示在终端屏幕, 可以用于查看和复制, 不需要可以去掉
" 好处：误删什么的，如果以前屏幕打开，可以找回
set t_ti= t_te=

" 启用鼠标
set mouse=a

set pastetoggle=<F2>            "    when in insert mode, press <F2> to go to
                                "    paste mode, where you can paste mass data
                                "    that won't be autoindented
" disbale paste mode when leaving insert mode
au InsertLeave * set nopaste
au InsertEnter * set paste


" 相对行号: 行号变成相对，可以用 nj/nk 进行跳转
set relativenumber number
au FocusLost * :set norelativenumber number
au FocusGained * :set relativenumber
" 插入模式下用绝对行号, 普通模式下用相对
autocmd InsertEnter * :set norelativenumber number
autocmd InsertLeave * :set relativenumber
function! NumberToggle()
  if(&relativenumber == 1)
    set norelativenumber number
  elseif(&number ==1)
    set norelativenumber nonumber
  else
    set relativenumber number  
  endif
endfunc
nnoremap <C-n> :call NumberToggle()<cr>

" autoload _vimrc
autocmd! bufwritepost ~/.vimrc source ~/.vimrc 

" theme主题
set background=dark
set t_Co=256

"A buffer becomes hidden when it is abandoned
set hidden

set autowriteall
